In [1]:
from platform import python_version

print(python_version())

3.8.8


In [2]:
if 5>2:
   print("five is grater than two")
if 5>2:
      print("five is grater than two")

five is grater than two
five is grater than two


In [3]:

#### first note when #### when two conditions are separates it must be verticaly 

if 5 >2:
    print("Five is grrater than two")
    print("Five is greater than two")

if 5 >2:
    print("Five is grrater than two")
     print("Five is greater than two")  # this does not work !


IndentationError: unexpected indent (<ipython-input-3-83e829642e7f>, line 9)

In [4]:
################################ second

x = 5
y = "Hello World!"

print (x)

print (y)    

5
Hello World!


In [5]:
###################################### third

x = 4  #x is of type int
x = "sally"
print(x)


sally


In [6]:
#################################### 5th

x = 5
y = "John"

print(type(x))
print(type(y))

<class 'int'>
<class 'str'>


In [7]:
################################### 6th 
                                
x, y, z = "orage","Banana","Cherry"
print(x)                           
print(y)                           
print(z)      

orage
Banana
Cherry


In [8]:
x = y = z =" Orange"
print(x)
print(y)
print(z)

 Orange
 Orange
 Orange


In [9]:
fruits = ["apple", "banana","cherry"]

x, y , z = fruits

print(x)
print(y)
print(z)


apple
banana
cherry


In [10]:
############################### wow very nice
x = "awsome"
print("python is " + x)

python is awsome


In [12]:
################################  how to do calculations problems

# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)   #this is the power function

# How much is your $100 worth after 7 years?

10
0
15
5.0
4
16


In [13]:
height = 1.79
weight = 7.42

bmi = weight/ height **2
print(bmi)
type("bmi")

2.3157829031553323


str

In [14]:
x = "Python is"

y = "awesome"

z = x + y

print(z)


Python isawesome


In [15]:
x = 5    
y = 10

print(x+y)

15


In [16]:
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)


Python is fantastic
Python is awesome


In [17]:

def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)


######################

day_of_week = 5
type(day_of_week)

x = "body mass index"
z = True


type(z)

Python is fantastic


bool

In [18]:
##########################  Global Variables  ?????

x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()


Python is awesome


In [19]:
###################################### 4th

x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

In [20]:
x = 5
print(type(x))

<class 'int'>


In [21]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [22]:
x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>


In [23]:
x = 1.10
y = 1.0
z = -35.59

print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [24]:
#( https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-2-python-lists?ex=2 )

##  python list 
a = "is"
b = "nice"
my_List = ["my", "list",a,b]
print(my_List)

['my', 'list', 'is', 'nice']


In [25]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [26]:
#list of lists
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv]]

# Print out house
print (house)
# Print out the type of house

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0]]


In [27]:
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]
print(type(areas))

<class 'list'>


In [28]:
#Subsetting Lists
#the index and the negative indecies
x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!

'b'

In [29]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [30]:
x = ["a", "b", "c", "d"]
print(x[1] + x[3])

bd


In [31]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [32]:
#The start index & end index.
x = ["a", "b", "c", "d"]
print(x[0])
print(x[1:3])

a
['b', 'c']


In [33]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [34]:
# Slicing and dicing (2)
x = ["a", "b", "c", "d"]
x[:2]


['a', 'b']

In [35]:
# Slicing and dicing (2)
x = ["a", "b", "c", "d"]

x[2:]


['c', 'd']

In [36]:
# Slicing and dicing (2)
x = ["a", "b", "c", "d"]
x[:]

['a', 'b', 'c', 'd']

In [37]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]


In [38]:
x[2][0]

'g'

In [39]:
x[2][:2]

['g', 'h']

In [40]:
x = ["a", "b", "c", "d"]

In [41]:
x[1]

'b'

In [42]:
x[-3]

'b'

In [43]:
# x[1] & x[-3] are the same result
#Subsitting list

fam = ["lis",1.73,"emma", 1.68,"mom",1.71, "dad",1.89] # I write the list but this list will not appear in the output


In [44]:
fam                                                    # this will show the list as an output

['lis', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [45]:
# each element in side the list has an index 
fam[1]   #the first

1.73

In [46]:
fam[2]   #the second element

'emma'

In [47]:
fam[1]
fam[2]         # the program will show just the second element

'emma'

In [48]:
fam[-1]   #to get the last element as a negative Index

1.89

In [49]:
fam[3:5]    # the 5th index is note included

[1.68, 'mom']

In [50]:
fam[1:5]         #[start:end]

[1.73, 'emma', 1.68, 'mom']

In [51]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [52]:
# Print out second element from areas
areas[1]

11.25

In [53]:
# Print out second element from areas
print(areas[1])

11.25


In [54]:
# Print out last element from areas
print(areas[-1])

9.5


In [55]:
# Print out the area of the living room
print(areas[5])

20.0


In [56]:
x = ["a", "b", "c", "d"]

In [57]:
print(x[1] + x[3])

bd


In [58]:
x[1] + x[3]

'bd'

In [59]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [60]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [61]:
#Slicing and dicing (2)

x = ["a", "b", "c", "d"]


In [62]:
x[:2]

['a', 'b']

In [63]:
x[2:]

['c', 'd']

In [64]:
x[:]

['a', 'b', 'c', 'd']

In [65]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[6:]

print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [66]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]


In [67]:
x[2][0]


'g'

In [68]:
x[2][:2]

['g', 'h']

In [69]:
# Lists Manipulating 
# change list Elements
# Add list elements
# remove element list

In [70]:
# Replace list elements
x = ["a", "b", "c", "d"]

In [71]:
x[1] = "r"

In [72]:
x

['a', 'r', 'c', 'd']

In [73]:
x[2:] = ["s", "t"]

In [74]:
x

['a', 'r', 's', 't']

In [75]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1]=10.50

print(areas)

# Change "living room" to "chill zone"
areas[4]= "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [76]:
# Extend a list

In [77]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
print(y)

['a', 'b', 'c', 'd', 'e', 'f']


In [78]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse",24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage",15.45] 

In [79]:
#Delete list elements

x = ["a", "b", "c", "d"]


In [80]:
del(x[1])

In [81]:
print(x)

['a', 'c', 'd']


In [82]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]


In [83]:
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [84]:
# Create areas_copy
areas_copy = list(areas)

In [85]:
print(areas_copy)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [86]:
# Change areas_copy
areas_copy[0] = 5.0


In [87]:
# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [88]:
# Functions
# nnthing new
# piece of reucable of code
# solves particular task

In [89]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

In [90]:
# Print out type of var1
print(type(var1))


<class 'list'>


In [91]:

# Print out length of var1
print(len(var1))


4


In [92]:

# Convert var2 to an integer: out2
out2 = int(var2)

In [93]:
print(type(out2))

<class 'int'>


In [94]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [95]:
?max

In [96]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]


In [97]:
# Paste together first and second: full
full = first + second

In [98]:
print(full)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [99]:
# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

In [100]:

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [101]:
# string to experiment with: place
place = "poolhouse"



In [102]:
# Use upper() on place: place_up
place_up = place.upper()

In [103]:
# Print out place and place_up
print(place)
print(place_up)


poolhouse
POOLHOUSE


In [104]:

# Print out the number of o's in place
print(place.count('o'))

3


In [105]:
#List Methods

# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]


In [106]:

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


In [107]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]


In [108]:

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)



In [109]:
# Print out areas
print(areas)



[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [110]:
# Print out areas
print(areas)



[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [111]:

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [112]:
#Import package

In [113]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2 * r * math.pi

# Calculate A
A = math.pi * r ** 2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [114]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


In [115]:
my_inv([[1,2], [3,4]])

NameError: name 'my_inv' is not defined

In [116]:

from scipy.linalg import inv as my_inv


In [117]:
my_inv([[1,2], [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [118]:
# First NumPy Array
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a Numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [119]:
#Python Packages and the import Statement
# math (mathematical functions)
#numpy (the numerical package)
#scipy (the scientific package)
#matplotlib (the plotting package)


In [120]:
sqrt (5)

NameError: name 'sqrt' is not defined

In [121]:
import math as mt
mt. sqrt (5)

2.23606797749979

In [122]:
mt. cos(mt. pi )

-1.0

In [123]:
from math import sqrt
print(sqrt (5))


print(cos( pi )) #now this will not work

2.23606797749979


NameError: name 'cos' is not defined

In [124]:
from math import sqrt ,cos , sin
print( sqrt (5) ,cos(0) , sin(0.3))


2.23606797749979 1.0 0.29552020666133955


In [125]:
from math import*    #(*) stands for “everything”.
print (sqrt (5))
print (cos( pi ))

2.23606797749979
-1.0


In [126]:
# height_in and weight_lb are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

NameError: name 'height_in' is not defined

In [127]:
x = [4 , 9 , 6, 3, 1]
x[1]


9

In [128]:
import numpy as np
y = np.array(x)


In [130]:
y[1]

9

In [131]:
print(y)

[4 9 6 3 1]


In [132]:
# as an rexample for list Recap
Height= [1.73,1.68,1.71,1.89,1.79]

print(Height)

Weight= [65.4,59.2,63.6,88.4,70]

print(Weight)

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 70]


In [133]:
Weight/Height**2     # the result like this because pyhton has no Idea to Calculations on Lists

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [134]:
# A way more elegant is to use NumPy (Numerical Python)
#It's a python package that among others, provides a alternative to the regular python list: the Numpy array
#the Numpy array is The Numpy array is pretty similar to the list , but has one additional feature: 
#you can perform calculations over  entire arrays.  #It's really easy, and super-fast as well.

In [135]:
import numpy as np
np_Height = np.array(Height)
np_Height


array([1.73, 1.68, 1.71, 1.89, 1.79])

In [136]:
np_Weight= np.array(Weight)
np_Weight

array([65.4, 59.2, 63.6, 88.4, 70. ])

In [137]:
bmi = np_Weight / np_Height**2

In [138]:
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.84700852]


In [140]:
python_list = [1,2,3]
nump_array = np.array([1,2,3])

In [141]:
python_list + python_list    #pay attention

[1, 2, 3, 1, 2, 3]

In [142]:
nump_array + nump_array      #pay attention

array([2, 4, 6])

In [143]:
x = ["a", "b", "c"]
x[1]


'b'

In [144]:
#      (  https://github.com/AhmetFurkanDEMIR/Numpy/blob/master/Numpy.ipynb   )

In [145]:
import numpy as np
a = np.array([1,2,3,4]) # numpy array oluşturma
b = np.array([7,8,9,10,8]) # numpy array oluşturma
print(a)
print(b)

[1 2 3 4]
[ 7  8  9 10  8]


In [146]:
a*b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [147]:
import numpy as np
# as an rexample for list Recap
np_height= np.array([1.73,1.68,1.71,1.89,1.79])

np_weight= np.array([65.4,59.2,63.6,88.4,70])


In [148]:
type(np_height)

numpy.ndarray

In [149]:
print(type(np_weight))

<class 'numpy.ndarray'>


In [150]:
#2D Numpy array
np_2D = np.array([[1.73,1.68,1.71,1.89,1.79],[65.4,59.2,63.6,88.4,70]])

In [151]:
np_2D

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 70.  ]])

In [152]:
np_2D.shape

(2, 5)

In [153]:
# 2 rows & 5 colums

In [154]:
np.array([[1.73,1.68,1.71,1.89,1.79],[65.4,59.2,63.6,88.4,70]])

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 70.  ]])

In [155]:
np_2D[0]     #the first list is the 0    and the second is 1

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [156]:
np_2D[1]

array([65.4, 59.2, 63.6, 88.4, 70. ])

In [157]:
np_2D[0][1]    # wow

1.68

In [158]:
np_2D[0,1]  # altrnative way 

# the value befor the comma specifies the row & after the comma specifies the colum

1.68

In [159]:
# if we want the first and thired colum
np_2D[:,1:3] 

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [160]:
np_2D[1,:]   # the first row

array([65.4, 59.2, 63.6, 88.4, 70. ])

In [161]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [162]:
# Import numpy
import numpy as np

In [163]:
# Create a 2D numpy array from baseball: np_baseball
np_2D = np.array(baseball )
#or np_2D = np.array([[180, 78.4],[215, 102.7],[210, 98.5],[188, 75.2]])

In [164]:
# Print out the type of np_baseball
print(type(np_2D))

# Print out the shape of np_baseball
print(np_2D.shape)

<class 'numpy.ndarray'>
(4, 2)


In [165]:
#### or another way

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [166]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [167]:
#Subsetting 2D NumPy Arrays
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:,0]

array(['a', 'c'], dtype='<U1')

In [168]:
import numpy as np
np_mat = np.array([[1, 2], [3, 4],[5, 6]])

In [169]:
np_mat * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [170]:
np_mat + np.array([10, 10])


array([[11, 12],
       [13, 14],
       [15, 16]])

In [171]:
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [172]:
import numpy as np
x = [1, 4, 8, 10, 12]


In [173]:
np.mean(x)


7.0

In [174]:
np.median(x)

8.0

In [175]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array


# Import numpy package
import numpy as np
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
# Create np_baseball (3 cols)

In [176]:
np_baseball = np.array(baseball)



In [177]:

np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))


198.25
199.0


In [178]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = None
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = None
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = None
print("Correlation: " + str(corr))

Average: 198.25
Median: None
Standard Deviation: None
Correlation: None


In [179]:
# heights and positions are available as lists
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]
# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 184.0
